/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.14.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.api;

import org.openapitools.model.Category;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.lang.Nullable;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import javax.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2025-09-17T12:29:00.555895+02:00[Europe/Madrid]", comments = "Generator version: 7.14.0")
@Validated
@Tag(name = "Categories", description = "the Categories API")
public interface CategoriesApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * DELETE /categories/{categoryId} : Borrar categoría
     *
     * @param categoryId  (required)
     * @return Categoría eliminada (status code 204)
     */
    @Operation(
        operationId = "categoriesCategoryIdDelete",
        summary = "Borrar categoría",
        tags = { "Categories" },
        responses = {
            @ApiResponse(responseCode = "204", description = "Categoría eliminada")
        }
    )
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = "/categories/{categoryId}"
    )
    
    default ResponseEntity<Void> categoriesCategoryIdDelete(
        @Parameter(name = "categoryId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("categoryId") String categoryId
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * PATCH /categories/{categoryId} : Modificar categoría
     *
     * @param categoryId  (required)
     * @param category  (required)
     * @return Categoría actualizada (status code 200)
     */
    @Operation(
        operationId = "categoriesCategoryIdPatch",
        summary = "Modificar categoría",
        tags = { "Categories" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Categoría actualizada")
        }
    )
    @RequestMapping(
        method = RequestMethod.PATCH,
        value = "/categories/{categoryId}",
        consumes = { "application/json" }
    )
    
    default ResponseEntity<Void> categoriesCategoryIdPatch(
        @Parameter(name = "categoryId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("categoryId") String categoryId,
        @Parameter(name = "Category", description = "", required = true) @Valid @RequestBody Category category
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * GET /categories : Listar categorías
     *
     * @return Lista de categorías (status code 200)
     */
    @Operation(
        operationId = "categoriesGet",
        summary = "Listar categorías",
        tags = { "Categories" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Lista de categorías", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = Category.class)))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/categories",
        produces = { "application/json" }
    )
    
    default ResponseEntity<List<Category>> categoriesGet(
        
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "[ { \"name\" : \"name\", \"id\" : \"id\", \"parentId\" : \"parentId\" }, { \"name\" : \"name\", \"id\" : \"id\", \"parentId\" : \"parentId\" } ]";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * POST /categories : Crear categoría
     *
     * @param category  (required)
     * @return Categoría creada (status code 201)
     */
    @Operation(
        operationId = "categoriesPost",
        summary = "Crear categoría",
        tags = { "Categories" },
        responses = {
            @ApiResponse(responseCode = "201", description = "Categoría creada")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/categories",
        consumes = { "application/json" }
    )
    
    default ResponseEntity<Void> categoriesPost(
        @Parameter(name = "Category", description = "", required = true) @Valid @RequestBody Category category
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
